FROM golang:1.16 as build

RUN apt-get update && apt-get install -y ninja-build

WORKDIR /go/src
RUN git clone https://github.com/drewmeltpool/ninja
WORKDIR /go/src/ninja
RUN go get -u ./build/cmd/bood

WORKDIR /go/src/horizontal-scale
COPY . .

WORKDIR /go/src/horizontal-scale/integration

ENTRYPOINT bood 2>&1 | tee integration.log
